#
# ATTENTION: This is an autogenerated file. See original at
#            https://github.com/maplibre/martin/blob/main/.github/files/homebrew.martin.rb.j2
#

class Martin < Formula
  current_version="0.15.0"

  desc "Blazing fast and lightweight tile server with PostGIS, MBTiles, and PMTiles support, plus an mbtiles tool"
  homepage "https://github.com/maplibre/martin"

  on_macos do
    on_arm do
      sha256 "a429043626414e311272d76c9babaebb9af6ecb0acb49719a2335879896c39b0"
      url "https://github.com/maplibre/martin/releases/download/v#{current_version}/martin-aarch64-apple-darwin.tar.gz"
    end
    on_intel do
      sha256 "8005c74ea38c4bf6b6606c249e3607f90cfede7ebdb121d8305f183e09cdf8cd"
      url "https://github.com/maplibre/martin/releases/download/v#{current_version}/martin-x86_64-apple-darwin.tar.gz"
    end
  end

  on_linux do
    on_arm do
      sha256 "b1b89ad17d9826f7ea88768290ab1639989df9e38a37e2893e1f6f06fb2ca605"
      url "https://github.com/maplibre/martin/releases/download/v#{current_version}/martin-aarch64-unknown-linux-musl.tar.gz"
    end
    on_intel do
      sha256 "2085286332c2a42f78039c7ce447f9e795af6ab6d27e2b2e8feea9222c88b2b3"
      url "https://github.com/maplibre/martin/releases/download/v#{current_version}/martin-x86_64-unknown-linux-musl.tar.gz"
    end
  end

  version "#{current_version}"

  def install
    bin.install "martin"
    bin.install "martin-cp"
    bin.install "mbtiles"
  end

  def caveats; <<~EOS
    Martin requires a database connection string.
    It can be passed as a command-line argument or as a DATABASE_URL environment variable.
      martin postgres://postgres@localhost/db
  EOS
  end

  test do
    `#{bin}/martin --version`
    `#{bin}/martin-cp --version`
    `#{bin}/mbtiles --version`
  end
end
