#
# ATTENTION: This is an autogenerated file. See original at
#            https://github.com/maplibre/martin/blob/main/.github/files/homebrew.martin.rb.j2
#

class Martin < Formula
  current_version="0.11.2"

  desc "Blazing fast and lightweight tile server with PostGIS, MBTiles, and PMTiles support, plus an mbtiles tool"
  homepage "https://github.com/maplibre/martin"

  on_macos do
    on_arm do
      sha256 "77ad2f4f8f5e19afe669ad2a39fa9bf4293798f98d067cce6d25a101f526d6ad"
      url "https://github.com/maplibre/martin/releases/download/v#{current_version}/martin-aarch64-apple-darwin.tar.gz"
    end
    on_intel do
      sha256 "8b6b3fb7b278d4508873498b3b9ad8301f7536700eb11263d3d29c5587cd84eb"
      url "https://github.com/maplibre/martin/releases/download/v#{current_version}/martin-x86_64-apple-darwin.tar.gz"
    end
  end

  on_linux do
    on_arm do
      sha256 "d821a4d1cc562cfff3fc7685374bb43266ec1c515e99b78f4be5d79de61f298c"
      url "https://github.com/maplibre/martin/releases/download/v#{current_version}/martin-aarch64-unknown-linux-musl.tar.gz"
    end
    on_intel do
      sha256 "a5494bcfa7f7192459fbcf2628846cf202ebfd59ecab64eccd27254858cf4db5"
      url "https://github.com/maplibre/martin/releases/download/v#{current_version}/martin-x86_64-unknown-linux-musl.tar.gz"
    end
  end

  version "#{current_version}"

  def install
    bin.install "martin"
    bin.install "mbtiles"
  end

  def caveats; <<~EOS
    Martin requires a database connection string.
    It can be passed as a command-line argument or as a DATABASE_URL environment variable.
      martin postgres://postgres@localhost/db
  EOS
  end

  test do
    `#{bin}/martin --version`
    `#{bin}/mbtiles --version`
  end
end
