#
# ATTENTION: This is an autogenerated file. See original at
#            https://github.com/maplibre/martin/blob/main/.github/files/homebrew.martin.rb.j2
#

class Martin < Formula
  current_version="1.0.0"

  desc "Blazing fast and lightweight tile server with PostGIS, MBTiles, and PMTiles support, plus an mbtiles tool"
  homepage "https://github.com/maplibre/martin"

  on_macos do
    on_arm do
      sha256 "756d4f0c73396eca6b34ec4f512f03fc619574e386646d8c441611a48ba49a8f"
      url "https://github.com/maplibre/martin/releases/download/martin-v#{current_version}/martin-aarch64-apple-darwin.tar.gz"
    end
    on_intel do
      sha256 "1e3c955a22988b46624c4a3df5bc4fd6880c286f33cb51aa5510c6eda3b8cfea"
      url "https://github.com/maplibre/martin/releases/download/martin-v#{current_version}/martin-x86_64-apple-darwin.tar.gz"
    end
  end

  on_linux do
    on_arm do
      sha256 "991957c0c285c2c949dcc6b326980850925af5ab5c7b66ebf1cf31465820a727"
      url "https://github.com/maplibre/martin/releases/download/martin-v#{current_version}/martin-aarch64-unknown-linux-musl.tar.gz"
    end
    on_intel do
      sha256 "9ef58e23cf79647a5e993d5c201a72a38398c189a4678d0c11e2dae82fd0b120"
      url "https://github.com/maplibre/martin/releases/download/martin-v#{current_version}/martin-x86_64-unknown-linux-musl.tar.gz"
    end
  end

  version "#{current_version}"

  def install
    bin.install "martin"
    bin.install "martin-cp"
    bin.install "mbtiles"
  end

  def caveats; <<~EOS
    Martin requires a database connection string.
    It can be passed as a command-line argument or as a DATABASE_URL environment variable.
      martin postgres://postgres@localhost/db
  EOS
  end

  test do
    `#{bin}/martin --version`
    `#{bin}/martin-cp --version`
    `#{bin}/mbtiles --version`
  end
end
